
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Quaerendo invenietis
#email: candycode@gmail.com
description: études in code
baseurl: /bwv1079 # the subpath of your site, e.g. /blog
url: ugovaretto-blogs.github.io # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username: ugovaretto

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
# Search settings
tipue_search:
  include:
    pages: true
    posts: true
    files: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile~
   - Gemfile
   - Gemfile.lock
   - node_modules
   - .jekyll-cache
   - __tmp
   - .DS_Store
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#
#Add line numbers: works but layout messed up with current theme
#same as using
#{% highlight javascript linenos %}
#    function some(code) { /*goes here*/ }
#    let x = 21;
#{% endhighlight %}
#markdown: kramdown
#kramdown:
#    highlighter: rouge
#    syntax_highlighter_opts:
#        block:
#            line_numbers: true
